networks:
    gamma:
    mat:
services:
    backend:
        build:
            context: ./go-backend
        image: linkit_backend:dev
        network_mode: "service:frontend"
        volumes:
            - ./backend:/usr/src/app
        environment:
            ADMINS: admin
            REDIRECT_URL: "localhost:3001"
            OIDC_CLIENT_ID: "id"
            OIDC_CLIENT_SECRET: "secret"
            OIDC_REDIRECT: "http://localhost:3001/auth/account/callback"
            OIDC_ISSUER: "https://auth.chalmers.it"
            DB_USER: postgres
            DB_PORT: 5432
            DB_PASS: example
            DB_NAME: bookit
            DB_HOST: db
            REDIS_URI: redis:6379
        depends_on:
            - redis
            - db
    frontend:
        build:
            context: ./frontend
            dockerfile: dev.Dockerfile
        image: linkit_frontend:dev
        networks:
            - mat
        ports:
            - 3001:3000
            - 4000:4000
            - 4001:4001
        volumes:
            - ./frontend/src:/usr/src/app/src
            - ./frontend/public:/usr/src/app/public
    adminer:
        image: adminer
        ports:
            - 8085:8080
        networks:
            - mat
    db:
        image: postgres:12
        restart: always
        networks:
            - mat
        environment:
            POSTGRES_DB: bookit
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: example
        ports:
            - 5432:5432 # Used by datagrip
    redis:
        image: redis:5.0.8
        networks:
            - mat
        ports:
            - 6379:6379
